### ISSUE TITLE
TASK-2: Setup GraphQL

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#10]
**Task Description**

As a developer, I want GraphQL to be set up for communication between the front-end and back-end applications so that we can take advantage to GraphQL's powerful feature set when querying information.

**Acceptance Criteria**

- [ ] Have a working GraphQL setup
- [ ] Have functioning GraphQL calls 
- [ ] Have mock data to test
