### ISSUE TITLE
TASK-26: Setup database seeding

### ISSUE THREAD

**Issue by r-saba** [RGPosadas/LitterRally#102]
**Task Description**

As a developer, I want to be able to easily generate mock data within the database

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](create-mockup-link)
