### ISSUE TITLE
TASK-3: Setup TravisCI to lint, test and build projects when relevant

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#11]
**Task Description**

As a developer, I want the correct projects to be linted, tested and built depending on the context so that resources are utilized optimally.

**Extra Description**

The Nx CLI offers a powerful feature called affected, where Nx determines what projects in your workspace were affected by newly introduced changes so that only the relevant parts of the codebase are linted, tested and built. Nx does it by comparing the current HEAD with a BASE, both of which can be set manually. By default, the BASE is master, but this isn't always going to be accurate, since features branches will be merged into develop, not master. In such cases, develop should be the BASE, so that the correct diff can be calculated.

Hints:
* TravicCI lets you set environment variables to 
* https://docs.travis-ci.com/user/docker/
* https://nx.dev/angular/cli/affected

**Acceptance Criteria**
Modify the travis config yaml to do the following:
* [ ] If the current branch is master, lint, test and build all projects
* [ ] If the current branch is develop, only lint, test and build affected projects, and set BASE to master (default)
* [ ] If the current branch is a feature branch, only lint, test and build affected projects, and set BASE to develop (default)

**Comment by cristian-aldea** [comment]
Removed the following AC from the ticket:
* [ ] Travis needs to trigger builds on DockerHub when appropriate (see above). Look if dockerhub can be triggered to build a project instead of listening to commits.

since it is covered by #50
