### ISSUE TITLE
TASK-29: Login Backend

### ISSUE THREAD

**Issue by bit172** [RGPosadas/LitterRally#111]
**Task Description**

As a developer, I want the backend for logging in so that I work on the frontend logic.

**Acceptance Criteria**

- [ ] Have JWT Tokens
  - [ ] Access tokens present
  - [ ] Refresh tokens present
- [ ] Have a GraphQL mutation for logging in
- [ ] Have a REST route for refresh tokens
  - [ ] The route is reached via a POST request
  - [ ] A cookie is set on the client containing the refresh token
  - [ ] The cookie is secure on HTTPS and the cookie is only sent on this route 
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
