### ISSUE TITLE
TASK-30:  Frontend OAuth Login Logic

### ISSUE THREAD

**Issue by bit172** [RGPosadas/LitterRally#112]
**Task Description**

As a developer, I want OAuth logic in the front-end so that the backend is connected.

The OAuth process requires the user to leave the application for a short moment. The authentication service provider will send the user's requests back to our server where we will create an access token and redirect the user back to our client application with the token as a URL parameter.

**Acceptance Criteria**

- [ ] Have a frontend route that takes in an access token in the URL parameters
- [ ] The user is redirected to the homepage after logging in through OAuth
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
