### ISSUE TITLE
TASK-31: Local Login Frontend Logic

### ISSUE THREAD

**Issue by bit172** [RGPosadas/LitterRally#113]
**Task Description**

As a developer, I want local logic in the front-end so that the backend is connected.

Users can log in using email and password. This can be achieved using a GraphQL mutation since it is our own implementation of authentication.

**Sub-Tasks**
- [ ] 31.1: Users can login with local accounts
- [ ] 31.2: Users are redirected to the homepage after logging in

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
