### ISSUE TITLE
TASK-33: Set Event location backend

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#124]
**Task Description**

As a developer, I want to save location information in the backend so that event creation can be completed.

**Acceptance Criteria**
- [ ] Connects with Location frontend #29 
- [ ] Location is stored when an event is created 
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function

**Hints**
- Possible fields we need to store are: PlaceId, Location name, Lat Long.
- There are two distinct types for locations: google locations and [Lat,Long] coords. Look into how that can be represented in typeORM

**Comment by cristian-aldea** [comment]
From my research, a common way to store geocoordites in MySQL would be to use points: https://dev.mysql.com/doc/refman/8.0/en/spatial-type-overview.html

If we go with this, we're considering using transformers to convert the string into an object with lat/long fields, making it easier to work with
