### ISSUE TITLE
TASK-34: Setup GraphQL Codegen

### ISSUE THREAD

**Issue by bit172** [RGPosadas/LitterRally#126]
**Task Description**

As a developer, I want GraphQL codegen so that I have easily accessible hooks to use on the frontend.

**Acceptance Criteria**

- [ ] GraphQL Codegen setup
- [ ] .gql files present for queries/mutations
- [ ] Auto generated .tsx file present
