### ISSUE TITLE
TASK-36: Event Preview Page

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#128]
**Task Description**

As a developer, I want to use the event-page component and create the Event Preview page so that users are able to see all the details of an event.

**Subtasks**

- [ ] 36.1 Route to events/id when you click on an event card
- [ ] 36.2 Implement a route for events/id which will show you the Event Preview page
- [ ] 36.3 Query an event by id when event page is used in `Preview` mode
- [ ] 36.4 Implement conditional behaviour for `Preview` mode

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=533%3A6528)
