### ISSUE TITLE
TASK-37: Implement image fetching from backend

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#133]
**Task Description**

As a developer, I want to be able to query images from the backend media server so that user-generated content can be shown in the application.

**Subtasks**

- [ ] 37.1 Create endpoint in backend for fetching images from the media server
- [ ] 37.2 Replace placeholder images currently in the application with actual functioning queries to the backend for the relevant photo.

**Acceptance Criteria**
- [ ] Implementation of the endpoint should use graphql ideally.
    - If that's not possible, make the endpoint using express or nestjs.
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function

Hints:
* Research if file fetching is possible with graphql
