### ISSUE TITLE
TASK-5: Setup Storybook (UI Component Tests)

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#14]
**Task Description**

As a developer, I want to setup Storybook so that it enables us to create robust, reusable, and testable UI components.

**Acceptance Criteria**

- [ ] Setup Storybook UI component tests
- [ ] Travis runs all runnable tests on CI
- [ ] Setup a Storybook knowledge handover meeting with the team
- [ ] Documentation exists as to how to implement and run Storybook tests

**Comment by RGPosadas** [comment]
FYI: We will only implement this if we have a need for it (ie. when we finally have multiple UI components).

**Comment by RGPosadas** [comment]
Closing as this was completely optional. As we near the end of the project, we don't have time for optional tickets.
