### ISSUE TITLE
TASK-39: Setup Machine Learning Training 

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#143]
**Task Description**

As a developer, I want to setup training a model so that it can be used in the application.

**Subtasks**

- [ ] 39.1 Gather Data
- [ ] 39.2 Setup training pipeline: From data and training, get a model that can recognize objects and run in the browser
- [ ] 39.3 Setup Validation of the model

**Acceptance Criteria**

- [ ] Get a model that can be used in the app
- [ ] Documentation present where necessary

**Comment by cristian-aldea** [comment]
Progress report: We managed to get a model trained and functional using TensorFlow's Object Detection API. We also managed to convert the model to a tfjs format to run it in the browser.

One small problem is that some meta-information about the model (output Tensor names and format) is lost during conversion, which makes it a bit more difficult to process the output since it's naming is more cryptic

However, everything is working correctly, so this ticket will be closed soon
