### ISSUE TITLE
TASK-40: Production Optimization

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#144]
**Task Description**

As a developer, I want our application to be optimized for Production so that our users can have a good experience. 

**Subtasks**

- [x] 40.1 Update icons and backsplash
- [ ] 40.2 Get as many lighthouse checks as possible:
    - [x] Progressive Web App 
    -  [ ] Best practices 
    - [ ] Accessibility 
    - [ ] Performance
    - [x] SEO 
- [x] 40.3 Make sure the manifest.json is accurate

**Note**
We don't have to hit 100. Do what is easy, if it takes too long, then do not do it.

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function

Checks run on mullapp.com:
![image](https://user-images.githubusercontent.com/23544999/104128433-74a0cf00-5335-11eb-9f7a-8c3357543341.png)
