### ISSUE TITLE
TASK-41: Remove Ingress Backend Paths

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#150]
**Task Description**

As a developer, I want to remove the ingress backend paths so that there is no out-of-cluster connectivity to our backend.

**Acceptance Criteria**

- [ ] Backend connectivity is done only in-cluster using pod's [FQDN](https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/)
- [ ] All backend paths are removed from the ingress
- [ ] Documentation present where necessary

**Comment by RGPosadas** [comment]
Won't do as we already have authenticated routes.
