### ISSUE TITLE
TASK-42: Create Process to Handle Schema Changes in Prod Database

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#151]
**Task Description**

As a developer, I want to have a process in order to handle schema changes in our prod database so that sensitive data is not lost.

**Acceptance Criteria**

- [ ] [Synchronize schema](https://github.com/RGPosadas/Mull/pull/145/files#diff-d005e106222bf02b241ad6612404229852054fcf02758498a0b3246af9c414a6R33) toggle is set to false
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function

**Comment by RGPosadas** [comment]
Won't do as we currently don't have a userbase.
