### ISSUE TITLE
US-3.1: Announcements Page

### ISSUE THREAD

**Issue by JimLau49** [RGPosadas/LitterRally#156]
**User Story Description**

As a host, I want the ability to make announcements so that I am able to keep participants up to date on my event.

**User Acceptance Flow**

1. Host types an announcement
2. Host clicks submit
3. Announcement appears on the announcement page

**Subtasks**
- [x] 3.1.1 Creating a new event creates an Announcements channel for that event.
- [x] 3.1.2  Text input is available only to host/cohosts (participants cannot add to the announcements chat).
- [x] 3.1.3 All previous announcements are queried/displayed and then a subscription is opened to show new announcements as they come. **(Ragith & Cindy)**
- [x] 3.1.4 Hosts can post messages (must verify that user is a host before saving message in the back-end) **(Ragith)**

**Acceptance Criteria**

- [ ] Host is able to post an announcement 
- [ ] Announcement is sent to users that are in the event 
- [ ] Participants of the event cannot send messages in announcements
- [ ] Seeder is updated for new entities
- [ ] User Acceptance Flow is respected
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] There must exist an automated Cypress acceptance test that tests the user acceptance flow
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2087%3A74417)

**Comment by RGPosadas** [comment]
https://www.apollographql.com/docs/react/data/subscriptions/#subscribing-to-updates-for-a-query
