### ISSUE TITLE
TASK-43: Event Host Announcements Front-end

### ISSUE THREAD

**Issue by JimLau49** [RGPosadas/LitterRally#157]
**Task Description**

As a developer, I want the event announcement page done so that I can connect a backend to it.

**Subtasks**

- [ ] 43.1 Slider to navigate between group chat and announcements
- [ ] 43.2 Announcements bubble shows up on page
- [ ] 43.3 Hosts can view a textbox where they can type their announcement
- [ ] 43.4 Add hamburger menu icon (but no functionality)  

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2087%3A74417)
