### ISSUE TITLE
TASK-44: Show 'Cancel' Button for My Events

### ISSUE THREAD

**Issue by osahtout** [RGPosadas/LitterRally#162]
**Task Description**

As a developer, I want to be able to cancel events that I've created.

**Note**: It is not a functional cancelling of the event. It is just the button styling.

**Acceptance Criteria**

- [ ] Mull button should show "cancel" for events I created
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](create-mockup-link)
