### ISSUE TITLE
TASK-45: Setup Authenticated Backend Routes

### ISSUE THREAD

**Issue by bit172** [RGPosadas/LitterRally#169]
**Task Description**

As a developer, I want authenticated backend routes so that some endpoints are protected.

**Acceptance Criteria**

- [ ] Authenticated routes can only be accessed by authenticated users
- [ ] Have a reusable Guard in the backend
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
