### ISSUE TITLE
TASK-48: Adapt App to notches

### ISSUE THREAD

**Issue by osahtout** [RGPosadas/LitterRally#177]
**Task Description**

As a developer, I want the application to take into consideration the notch so that it matches the mockups.

**Extra Description**

Because many phones include a notch, it forces the application to start below the notch ignoring some CSS. The application should adapt to this drop so that the CSS is not affected. 

see:
- https://dev.to/marionauta/avoid-notches-in-your-pwa-with-just-css-al7
- https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html

<img width="697" alt="image" src="https://user-images.githubusercontent.com/44760251/105918659-46dcab00-6002-11eb-888d-ad4371856c6f.png">

**Acceptance Criteria**

- [ ] Surrounding the notch should be white
- [ ] CSS should not be moved down if possible
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](create-mockup-link)
