### ISSUE TITLE
TASK-49: Refresh Homepage Scrolling up

### ISSUE THREAD

**Issue by osahtout** [RGPosadas/LitterRally#178]
**Task Description**

As a developer, I want to refresh the homepage (discover, upcoming, My events) when scrolling up far enough so that the user can update the page and get the latest update. 

**Extra Description**

It's a standard feature to allow the user to get the latest updates happening at their own will. Some developers say Android is already included however in iOS, it's not included. 

Example below used in outlook app even though the app updates real-time:
![Image from iOS](https://user-images.githubusercontent.com/44760251/105920103-c23f5c00-6004-11eb-86fb-8f7d902904c0.jpg)

**Acceptance Criteria**

- [ ] Scrolling up (seeing the events halfway down the page at least) will refresh the page.
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](create-mockup-link)

**Comment by RGPosadas** [comment]
Nice to have
