### ISSUE TITLE
TASK-50: Save Messages to Back-end

### ISSUE THREAD

**Issue by JimLau49** [RGPosadas/LitterRally#184]
**Task Description**

As a developer, I want to save messages to the backend so that they can be fetched from the frontend.

**Acceptance Criteria**
- [ ] Is reusable for announcements and group chats
- [ ] Messages are saved when they are created
- [ ] Messages can include images
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
