### ISSUE TITLE
TASK-52: Group Chat Back-end

### ISSUE THREAD

**Issue by JimLau49** [RGPosadas/LitterRally#187]
**Task Description**

As a developer, I want to save group messages in the backend so that it can be connected to the announcement page

**Acceptance Criteria**

- [ ] Connects with event host announcement front-end #186  
- [ ] Group messages are saved when an group message is submitted
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function

**Comment by RGPosadas** [comment]
No longer needed. Won't do.
