### ISSUE TITLE
TASK-53: User profile page front-end

### ISSUE THREAD

**Issue by JimLau49** [RGPosadas/LitterRally#188]
**Task Description**

As a developer, I want a user profile page so that I can connect a back-end to it.

**Subtasks**

- [ ] 53.1 Add fields buttons (portfolio, friends, misc)
- [ ] 53.2 Add settings button (no functionality) 
- [ ] 53.3 Add profile statistics ( portfolio, friends , hosting) counters

**Acceptance Criteria**

- [ ] User is able to view their profile statistics
- [ ]  Profile Header is a reusable component
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2048%3A0)
