### ISSUE TITLE
TASK-54: User Profile Page Back-end

### ISSUE THREAD

**Issue by JimLau49** [RGPosadas/LitterRally#189]
**Task Description**

As a developer, I want to save user profile information so that it can be accessed in the front-end.

**Subtasks**

- [x] 54.1 Profile picture is stored in the backend 
- [x] 54.2 User statistics are fetched from the backend  ( portfolio, friends, hosting)

**Acceptance Criteria**

- [ ] User profile is saved and able to be updated in the back-end 
- [ ] User profile can be fetched
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
