### ISSUE TITLE
TASK-55: Process TensorflowJS model output

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#190]
**Task Description**

As a developer, I want to process the output of a TensorflowJS (TFJS) model into a format that can be easily used to draw annotations on top of the camera feed so that the development of the ML tool can be simpler.

**Extra Description**

A new type, called DetectionResult, should be created to house information about a detection the model has made. It should have the following fields, among others:
- The label/class of the detection
- The bounding box of the detection, in pixels
- confidence
This is documented on our SAD lucidchart project, and will be updated if needed there

**Acceptance Criteria**

- [ ] Have utility methods and abstractions in place for processing model output
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
