### ISSUE TITLE
TASK-56: Display Model results 

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#191]
**Task Description**

As a developer, I want to display icons over detections from the model so that users can have visual feedback when pointing their camera at objects with the ML tool.

**Extra Description**

This ticket depends on data from #190, but that doesn't mean it can't be started, once the data type of a DetectionResult is defined, the implementation for this ticket can be started on mock data.

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/?node-id=533%3A7886)

**Comment by cristian-aldea** [comment]
For people working on this ticket, keep in mind that the shape for a prediction result has been documented here:
https://lucid.app/lucidchart/61a68588-ffd7-47de-94ae-0e73d0bd7864/view?page=~89t~u.QIMZ9#?folder_id=home&browser=icon

If it needs changing, let's discuss it so that #190  and this issue can proceed smoothly.
