### ISSUE TITLE
TASK-57: Add PlaceId Entries To Location Factory

### ISSUE THREAD

**Issue by osahtout** [RGPosadas/LitterRally#199]
**Task Description**

As a developer, I want both coordinates and placeId in the location table so that I can have a variety of entries in the database.

**Extra Description**

- Have a static array filled with random placeId's from the place API. Make sure to note of the address as well.
- Write an algorithm to randomly replace half the entries that have a coordinates Id with placeIds. Make sure to replace the title and remove the coordinates ID
- Done in the location.factory.ts
 

**Acceptance Criteria**

- [ ] Half the location entries have a placeId and the other half have coordinateId 
- [ ] The set replaced is random and not sequential
- [ ] Documentation present where necessary
