### ISSUE TITLE
TASK-58: Create Text Area Component

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#204]
**Task Description**

As a developer, I want a custom-test-area component so that it can be reused throughout the application.

**Subtasks**

- [ ] X.1 Subtask 1
- [ ] X.2 Subtask 2

**Acceptance Criteria**

- [ ] Task criteria #1
- [ ] Task criteria #2
...
- [ ] Task criteria #n
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](create-mockup-link)

**Comment by RGPosadas** [comment]
Nice to have
