### ISSUE TITLE
TASK-59: Save Channels to Back-end

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#210]
**Task Description**

As a developer, I want to be able to save channels so that the messaging backend logic can be complete.

**Acceptance Criteria**

- [ ] Channels can be created
- [ ] Channels are linked to posts
- [ ] Update Post TODOs and tests
- [ ] Reusable for announcements and group chats
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
