### ISSUE TITLE
TASK-60: Authentication for Subscription

### ISSUE THREAD

**Issue by JimLau49** [RGPosadas/LitterRally#215]
**Task Description**

As a developer, I want to add Authentication to the post subscription so that only users with the valid authToken can fetch the posts.

**Acceptance Criteria**

- [ ] Only validated users can fetch posts 
- [ ] Have a testable front-end subscription working 
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data

**Comment by JimLau49** [comment]
Estimated as a 2 with @r-saba
