### ISSUE TITLE
TASK-61: Emoji Support

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#223]
**Task Description**

As a developer, I want to add emoji support so that I can improve Müll's UI/UX.

**Subtasks**
- [x] 60.1 Emojis should be supported ONLY in these columns:
  - event.description
  - user.description
  - post.message
- [x] 60.2 An error message must be shown to show that emojis are not supported in these fields:
  - user.name
  - event.title

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
