### ISSUE TITLE
TASK-62: Apply Usability Testing Feedback

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#224]
**Task Description**

As a developer, I want to apply the feedback from usability testing so that I can improve Müll's UI/UX.

**Subtasks**

- [x] 62.1 Events should be sorted by start date
- [x] 62.2 Create event description input should be a textarea
- [x] 62.3 Look for a better Event Card "Join" icon
- [x] 62.4 On desktop, make the Müll logo clickable
- [x] 62.5 On mobile, create event calendar should not be vertically scrollable

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=534%3A6528)
