### ISSUE TITLE
TASK-63: Messages Main Menu Frontend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#225]
**Task Description**

As a developer, I want to add the swipe-able routes for the messages main menu page to toggle between `Direct Messages` and `Event Messages`.

**Acceptance Criteria**

- [x] Query all friends for searchable DM page
- [ ] Implement top header containing swipe-able routes
- [ ] Implement onclick event that redirect to DM/event-group-chat page (after channel is fully complete)
- [ ] Show "No events found" or "No DMs found" when queries are empty
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
- [ ] Must match [mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=3144%3A5)

**Comment by RGPosadas** [comment]
https://www.apollographql.com/docs/react/data/subscriptions/#subscribing-to-updates-for-a-query

**Comment by cristian-aldea** [comment]
Minor comment but I remember there was discussion about some complications in styling if we were to use swipeable routes for messaging. If it is the case that we run into trouble I'd say we can keep it to being simple buttons, since swiping isn't that essential the user flow
