### ISSUE TITLE
TASK-64: Messages Main Menu Backend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#226]
**Task Description**

As a developer, I want to setup the messages main page backend so that I can connect it to frontend.

**Acceptance Criteria**

- [ ] Query exists to get the latest message from a DM channel
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
- [ ] Must match [Mockup](create-mockup-link)
