### ISSUE TITLE
TASK-65: Identified Trash Frontend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#229]
**Task Description**

As a developer, I want a page to be made to show extra information about a type of waste so that #34 can be completed.

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2047%3A76571)

**Note**: Mock info is fine. No need to add analysis breakdown.
TODO: Update Figma
