### ISSUE TITLE
TASK-66: Click on the Waste Recognition Page

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#230]
**Task Description**

As a developer, I want to be able to press on trash icons when identifying trash so that I can setup the user flow for showing extra information to the user.

**Extra Description**

You'll need to add a mousedown listener on the canvas and do some math to check where the user clicked relative to the canvas, and in which detection box did the click happen

**Acceptance Criteria**

- [ ] User can press on the screen
- [ ] Pressing on the screen triggers an onclick that identifies which box they pressed on by console logging the object that they pressed
- [ ] Documentation present where necessary
- [ ] Unit tests are implemented for every new component and function
- [ ] The application should still work with seeded data

**Note**: Analysis breakdown might not be possible. So, do not take it into account.

Extra:
- Stackoverflow post which sorta explains what to do: https://stackoverflow.com/questions/24384368/simple-button-in-html5-canvas
