### ISSUE TITLE
TASK-67: Waste Identification Result Page

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#231]
**Task Description**

As a developer, I want a page to be made to show extra information about a type of waste so that #34  can be completed.

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
- [ ] Must match [Mockup](create-mockup-link)

**Comment by RGPosadas** [comment]
Closing, dupe of #229
