### ISSUE TITLE
TASK-69: Searchable DMs Frontend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#233]
**Task Description**

As a developer, I want to have searchable DMs frontend.

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
- [ ] Must match [mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2087%3A74353)
