### ISSUE TITLE
TASK-70: Chat Bubble List Reusable component

### ISSUE THREAD

**Issue by r-saba** [RGPosadas/LitterRally#238]
**Task Description**

As a developer, I want a component to render a list of messages. 
This component accepts a list of messages and renders a list of chat-bubbles.

**Acceptance Criteria**

- [ ] Renders a list of chat-bubbles
- [ ] chat-bubbles of current user have a different style to easily identify current user messages
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2087%3A74417)

**Note**: This component does not query for messages, it receives a list of message data as a prop
