### ISSUE TITLE
TASK-71: DMs Backend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#247]
**Task Description**

As a developer, I want to setup the DMs backend.

**Subtasks**

- [x] 71.1 Single table inheritance for DirectMessageChannel and EventChannel
- [x] 71.2 Users are related to channels

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
