### ISSUE TITLE
TASK-72: Time Picker Slider

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#248]
**Task Description**

As a developer, I want to have a custom time picker slider so that picking time is consistent across all browsers.

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
