### ISSUE TITLE
TASK-73: Events on a Map Frontend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#265]
**Task Description**

As a developer, I want to setup the pages for events on a map frontend.

**Subtasks**

- [ ] X.1 Subtask 1
- [ ] X.2 Subtask 2

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
- [ ] Must match mockups:
   * [Events when map is zoomed out](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2000%3A348031)
   * [Events when map is zoomed in](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2000%3A348175)
