### ISSUE TITLE
TASK-74: Events on a Map Backend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#266]
**Task Description**

As a developer, I want to setup the backend for events on a map.

**Subtasks**

- [ ] X.1 Subtask 1
- [ ] X.2 Subtask 2

**Acceptance Criteria**

- [ ] Security is handled in the backend
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
