### ISSUE TITLE
TASK-76: View Other User Profiles Frontend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#272]
**Task Description**

As a developer, I want to setup the frontend for viewing other users' profiles

**Acceptance Criteria**

- [ ] user-relationship buttons exist
- [ ] Modal exists
- [ ] If queries already exist, use them already instead of using placeholders (for example, getting portfolio events)
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
- [ ] Must match mockups:
   - [Add Friend ](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58846)view
   - [Pending](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58851) view
   - [Friends](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58834) view
   - [Remove Friend modal](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58839) view
