### ISSUE TITLE
TASK-77: View Other User Profiles Backend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#275]
**Task Description**

As a developer, I want to setup the user-relationship queries to connect to the frontend.

**Acceptance Criteria**

- [ ] getUserRelationship query exists and query the appropriate relationship between the logged in user has with the other user
- [ ] Security is handled in the backend
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data

**Hint**

![image](https://user-images.githubusercontent.com/23544999/111036389-f9b76b80-83ec-11eb-8cac-f2e7cb76b3e9.png)
The easiest way to get a `user-relationship` query for this ticket seems to check the friendlists of the two users:
* If A has B in their friendlist, then A sent B a friend request (AB is in the table)
* If B has A in their friendlist, then B sent A a friend request (BA is in the table)
* If both A and B have each other as friends, then they are friends (AB + BA are in the table)
