### ISSUE TITLE
TASK-78: Add Friends Frontend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#276]
**Task Description**

As a developer, I want to create the pages for Add Friends.

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] Must match mockups:
   - "[Added Me + Pending Requests](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1596%3A5062)" view
   - "[Pending Request modal](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1695%3A83663)" view
   - "[Search Users](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1695%3A86144)" view
