### ISSUE TITLE
TASK-79: Add Friends Backend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#277]
**Task Description**

As a developer, I want to create the backend queries to support the pages for the frontend (#276) .

**Acceptance Criteria**

- [ ] Queries exist:
   - addFriend
   - removeFriend
   - getRelationships
- [ ] Security is handled in the backend
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
