### ISSUE TITLE
TASK-80: Friends List Frontend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#279]
**Task Description**

As a developer, I want to create the pages for the friends list.

**Acceptance Criteria**
- [ ] Page uses `useFriendsQuery`
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
- [ ] Must match mockups:
   - "[My Friend](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1588%3A4821)s" view
   - "[More info modal](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1596%3A4543)" view
