### ISSUE TITLE
TASK-81: Logout Button on Profile Page

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#282]
**Task Description**

As a developer, I want to have a functional logout button on the profile page so that I can end my session.

**Acceptance Criteria**
- [ ] Logout button exists underneath the Settings button
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
