### ISSUE TITLE
TASK-82: Modify EventCard and EventPage Depending on Event End Date

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#283]
**Task Description**

As a developer, I want to disallow users from joining past events on both the EventCard and EventPage components.

**Acceptance Criteria**
- [ ] Logic is present to remove buttons from past events
- [ ] Past events no longer show up on the discover, upcoming and my events pages
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58846)
