### ISSUE TITLE
TASK-83: Viewing Other User Profile Page Flows

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#284]
**Task Description**

As a developer, I want to setup the flows that will lead to viewing another user's profile page.

Flow #1: UserA is friends with UserB
1. UserA logs in
1. UserA goes to their Profile Page
1. UserA clicks on My Friends
1. UserA clicks on UserB's profile
1. UserA sees UserB's profile page 

Flow #2: UserA is not friends with UserB
1. UserA logs in
1. UserA goes to their Profile Page
1. UserA clicks on Add Friends
1. UserA types in UserB's name
1. UserA clicks on UserB's profile
1. UserA sees UserB's profile page 

Flow #3: Accessing UserB's profile through chatting pages
1. UserA is in a chat with UserB (either Direct Messages or Event Messages)
1. UserA clicks on UserB's avatar
1. UserA sees UserB's profile

**Acceptance Criteria**
- [ ] Connect pages to each other which will eventually lead to a user's profile page
- [ ] Flows are respected
- [ ] Update E2E test as needed
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function

**Comment by RGPosadas** [comment]
Closing since these flows have already been done in their respective tickets.
