### ISSUE TITLE
TASK-84: Improve Waste Recognition Model

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#286]
This is a continuation of #64. It is a slow and steady ticket that aims to continuously improve part of our stack and will be close at the end of the sprint.

**Task Description**

As a developer, I want to improve the performance of our machine learning tool so that users can have a better experience with our application.

**Extra Description**

Currently, the model can detect certain objects and isn't always accurate or confident. Some of these issues can't be resolved, since the model is very fast and small (since we're aiming for a good mobile experience). However, we can gather more data to fix some of these issues.

**Subtasks**

- [x] Repository of training data is available: [link](https://liveconcordia-my.sharepoint.com/:f:/g/personal/c_aldea_live_concordia_ca/Epe8coZExh1OuU1rVWnqHUcBzhvUUB0_Sumgw7V-svMKqw?e=BMtfxI) (password given on slack)
- [ ] Gather as much data as possible for the following categories in the Pascal format (list to be expanded as we find issues):
    - [ ] ...
- [ ] After gathering data, the deliverables will be updated with an accuracy report

**Notes**
- Good data source: https://storage.googleapis.com/openimages/web/index.html
    - Good tool to download from open images: https://pypi.org/project/openimages/
- Good tool to label data manually in the Pascal VOC format: https://github.com/tzutalin/labelImg
- Ideally ~2000 images per category. Get as many as you can.

**Comment by cristian-aldea** [comment]
After searching for data to integrate into the training, we only a few categories which would make sense to add from the Open Images dataset:
- fork
- spoon
- balloon

It would be nice to have more useful data on more common trash items (red solo cup, paper, etc.) but either this data isn't available, or isn't available in the format we need it in. This doesn't make data gathering on such items impossible, but it does make it time-consuming (either manually creating the data, or writing scripts to get available data in the right format). 

Due to the tightness of our deadlines, we have decided that there aren't any meaningful updates to do for the modal for now.
