### ISSUE TITLE
TASK-85: Reusable Modal Component

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#301]
**Task Description**

As a developer, I want to have a reusable modal component so that it may be used in pages that need modals.

**Subtasks**
- [ ] 85.1 Reusable modal component with rounded corners, x button, and common styling across all modals
- Specific modals for Friends:
   - [ ] 85.2 Reusable friend modal component with [1 button](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58839) exists
   - [ ] 85.3 Reusable friend modal component with [2 buttons](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1596%3A4543) exists

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] Must match mockups (see subtasks)

**NOTE**
The tickets blocked by this task is a soft-block as those tickets can technically implement their own modals.
