### ISSUE TITLE
TASK-86: Misc. UX/Styling Cleanup

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#314]
**Task Description**

As a developer, I want to fix the styling and improve the UX of:

- [ ] 86.1 On Discover/Upcoming/My Events, show “No events found” when queries are empty
- [ ] 86.2 Smaller Mull logo and nav bar on desktop
- [ ] 86.3 Remove all back buttons when on desktop
- [ ] 86.4 All buttons and inputs should have feedback when you hover and click
- [ ] 86.5 Remove all share buttons
- [ ] 86.6 All text input limits should match backend varchar limits
- [ ] 86.7 Remove Map button and move the buttons around according to this [mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=3691%3A87700)

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
