### ISSUE TITLE
TASK-87: Messages Page UX/Styling Cleanup

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#315]
**Task Description**

As a developer, I want to fix the styling and improve the UX of the messages pages:
- [ ] 87.1 Remove chatbox autofill
- [ ] 87.2 Don’t allow empty spaces without photos to be sent 
- [ ] 87.3 Add username to chat bubbles
- [ ] 87.4 Text input area should grow to a certain size if the message is really long (keeping in mind the backend varchar length)
- [ ] 87.5 Text message limit should be shown (or figure out a way to send long messages)
- [ ] 87.6 Profile pics are clickable and should redirect to their respective profile page
- [ ] 87.7 Remove bottom nav when keyboard is showing (mobile)

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
