### ISSUE TITLE
TASK-88: CreateEvent Page UX/Styling Cleanup

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#316]
**Task Description**

As a developer, I want to fix the styling and improve the UX of the CreateEvent page:
- [ ] 87.1 Move “Location” above “Description”
- [ ] 87.2 Add “Restriction” title above pillbox
- [ ] 87.3 Pillbox should grow along with the input boxes
- [ ] 87.4 Slightly wider spacing between title and inputs
- [ ] 87.5 When done creating an event, redirect to My Events (not Home/Discover)
- [ ] 87.6 When image is not added to form, then user must see image error message

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
