### ISSUE TITLE
TASK-89: EventPage Review/Preview Styling/UX Cleanup

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#317]
**Task Description**

As a developer, I want to fix the styling and improve the UX of the EventPage review/preview pages:
- [ ] 89.1 Comment out unused SVG icons (messages + map)
- [ ] 89.2 Comment out "Invite Friend" row
- [ ] 89.3 Host’s avatar should be shown
- [ ] 89.4 On Preview: should highlight Home button 

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
