### ISSUE TITLE
TASK-90: EventCard Styling/UX Cleanup

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#318]
**Task Description**

I want to fix the styling and improve the UX of the EventCard component:

- [ ] 90.1 EventCard date border should be more modern (shadow instead of border and play around with it, see what looks best)
- [ ] 90.2  Use host/co-host/participant avatar images on EventMembers component instead of placeholder

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
