### ISSUE TITLE
TASK-91: Profile Page Styling/UX Cleanup

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#319]
**Task Description**

I want to fix the styling and improve the UX of the Profile page:

- [ ] 91.1  Restrict number of lines that can be added in the description despite character length

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
