### ISSUE TITLE
TASK-92: Loading Spinner

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#320]
**Task Description**

As a developer, I want to implement a loading spinner instead of just using a `Loading...` text div.

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
