### ISSUE TITLE
TASK-93: Improve 404 Page

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#321]
**Task Description**

As a developer, I want to improve our current 404 page to be stylized better. Currently, our 404 page is a simple div with `404 page not found` text. Make it look nice!

**Subtasks**

- [ ] 93.1 Invalid links should redirect to 404 page
   - [ ] Accessing a messaging page that the user does not have access to should give a 404
   - [ ] (other invalid path links)
 - [ ] 93.2 Have a button that redirects to homepage

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
