### ISSUE TITLE
TASK-94: Add Frontend Validation for Image Uploads

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#322]
**Task Description**

As a developer, I want to add a warning/error stating that the image the user wants to upload is bigger than 10MB, and it must be smaller than that.

We are using image upload in:
* Create event
* All message pages
* Edit profile

**Acceptance Criteria**
- [ ] File Sizes are validated everywhere images can be uploaded
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
