### ISSUE TITLE
TASK-95: Email Validation

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#323]
**Task Description**

As a developer, I want to have email validation so that users must own the emails they register with.

**HINT**: Use Concordia's SMTP server or use our gmail, and look into node-mailer

**Subtasks**

- [ ] 95.1 Have a workflow to send validation emails to users (create a HTML template)
- [ ] 95.2 Do not activate account until user is verified
- [ ] 95.3 Add isVerified boolean to user.entity
- [ ] 95.4 Create URL to validate user (magic link)
- [ ] 95.5 The email must come from @mullapp.com

**Acceptance Criteria**
- [ ] E2Es must still pass
- [ ] Security is handled in the backend (if backend ticket)
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
