### ISSUE TITLE
TASK-7: Create Navigation Bar

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#35]
**Task Description**

As a developer, I want to set up the navigation bar so that the component is ready for other user stories to be developed on top of it.

**Pre-requisites**

- [ ] React component hierarchy exists for devs to follow

**Acceptance Criteria**

- [ ] Nav bar shows all the buttons and each button is routed (but can lead to dead links)
- [ ] Documentation present for every new component and function
```
 * Description of Function/Component
 *
 * @param param1 Description of parameter 1
 * @param param2 Description of parameter 2
```
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/?node-id=534%3A6528)

**Comment by cristian-aldea** [comment]
Good progress done @leojrsilao , a few things left to do:
* Testing
* Documentation
* Confirming with @r-saba about the component hierarchy
