### ISSUE TITLE
TASK-8: Set Up Media Backend

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#36]
**Task Description**

As a developer, I want to set up a media backend so that it can support stories that uploads media.

**Acceptance Criteria**

- [ ] Media backend is set up and functional
- [ ] Can upload and download images
- [ ] Can be reachable through a backend endpoint
- [ ] Documentation present for every new component and function
```
 * Description of Function/Component
 *
 * @param param1 Description of parameter 1
 * @param param2 Description of parameter 2
```
- [ ] Unit and UI tests are implemented for every component and function
