### ISSUE TITLE
TASK-9: Create and Setup Local Dev Database

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#42]
**Task Description**

As a developer, I want to setup a local dev database so that we can start developing and storing our data.

**Acceptance Criteria**

- [ ] Database matches ER diagram
- [ ] Documentation for how to setup your own local database to work with our project
- [ ] Documentation present for every new component and function
```
 * Description of Function/Component
 *
 * @param param1 Description of parameter 1
 * @param param2 Description of parameter 2
```
