### ISSUE TITLE
TASK-11: Set Travis to trigger Docker builds

### ISSUE THREAD

**Issue by cindyslittleplanet** [RGPosadas/LitterRally#50]
**Task Description**

As a developer, I want Travis to trigger Docker builds, so that the appropriate images run on the dev and prod environments. 

**Acceptance Criteria**

- [ ] PRs build dev image tags
- [ ] Develop branch builds develop tags
- [ ] Master branch builds latest tags
- [ ] Documentation present

**Comment by RGPosadas** [comment]
https://docs.travis-ci.com/user/docker/

**Comment by RGPosadas** [comment]
Closing as Travis is long gone for our team, and only prod uses docker images.
