### ISSUE TITLE
TASK-12: Event Discovery page tabs

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#54]
**Task Description**

As a developer, I want the "Discover", "Upcoming", and "My events" tabs to be implemented so that other user story can be supported.

**Acceptance Criteria**

- [ ] The tabs are implemented for the discovery page and the user can swipe/tap to switch between tabs.
- [ ] Each tab is routed, but can lead to dead links or pages
- [ ] Documentation present for every new component and function
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=533%3A6528)
