### ISSUE TITLE
TASK-13: Update Navigation Bars

### ISSUE THREAD

**Issue by osahtout** [RGPosadas/LitterRally#58]
**Task Description**
As a developer, I want to update the mobile and desktop navigation bars so that it matches the updated mockups.

**Extra Description**
Since the Profile icon is now on the mobile upper nav bar and the Messages icon replaces it, both the desktop and mobile nav bars have to be updated.

**Pre-requisites**
- [ ] React component hierarchy exists for devs to follow

**Acceptance Criteria**

- [ ] Mull logo accommodates notches
- [ ] Nav bar shows all the buttons and each button is routed (but can lead to dead links)
- [ ] Documentation present for every new component and function
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/?node-id=534%3A6528)
