### ISSUE TITLE
TASK-14: Event Card

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#62]
**Task Description**

As a developer, I want to implement a generic event card component so that it can be available across the application to support other user stories.

**Acceptance Criteria**
- [ ] Documentation present for relevant new components and functions
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2000%3A343283)

**Comment by r-saba** [comment]
Closing this task since #65 was pushed to backlog
