### ISSUE TITLE
TASK-16: Gather Training data for the Waste Recognition Model

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#64]
**Task Description**

As a developer, I want to improve the object detection model by gathering data on objects it has trouble detecting so that it can be a useful tool.

**Acceptance Criteria**

- [x] Repository of training data is available: [link](https://liveconcordia-my.sharepoint.com/:f:/g/personal/c_aldea_live_concordia_ca/Evd3mpAYFE1MjbhUcxKisUQBRz2IVUegTL8FdK0yFa3ztg?e=XB4G2V) (password on Slack)
- [ ] Data is saved in the [Pascal VOC format ](https://roboflow.com/formats/pascal-voc-xml)
- [ ] Gather as much data as possible for the following objects in the Pascal format (list to be expanded as we go):
    - [x] Bottles
    - [x] Food
    - [x] Tin cans
    - [x] Box
    - [ ] ...
 - [ ] After gathering data, some form of accuracy report should be done to assess the performance of the model, and where improvements are needed

Hints:
* Converter which can convert between many standard formats: https://roboflow.com/formats/pascal-voc-xml
    * In general, many tools exist which can convert between different format (ex: "convert to Pascal VOC" on Google). If we can't find what we need, we can just write scripts ourselves and add it to "ml/trash-recognition".
* Good data source: https://storage.googleapis.com/openimages/web/index.html
* Good tool to download from open images: https://pypi.org/project/openimages/
* Good tool to label data manually in the Pascal VOC format: https://github.com/tzutalin/labelImg
* Or maybe even have other models annotate images for us 👀 https://scale.com/image
* ~500 photos minimum per object

**Comment by bit172** [comment]
Data was gathered. This ticket will be re-opened in the future to refine our model.
