### ISSUE TITLE
TASK-18: Multiple Registration Options Front-end 

### ISSUE THREAD

**Issue by r-saba** [RGPosadas/LitterRally#72]
**Task Description**

As a developer I want a UI to allow users to create an account using multiple registration options.

**Subtasks**
- [x] 18.1 Login page
- [x] 18.2 Registration page

**Acceptance Criteria**

- [ ] Documentation present for every new component and function where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2079%3A70811)
