### ISSUE TITLE
TASK-19: Multiple Registration Options Back-end

### ISSUE THREAD

**Issue by r-saba** [RGPosadas/LitterRally#73]
**Task Description**

As a developer, I want to develop the business logic for multiple registration options to be able to implement the user flow.

**Acceptance Criteria**
- [ ] Registration is possible using an existing service (Google, Twitter, Facebook) or email.
- [ ] Documentation present for every new component and function where necessary
- [ ] Unit tests are implemented.
