### ISSUE TITLE
TASK-20: Show Events as a list Back-end

### ISSUE THREAD

**Issue by r-saba** [RGPosadas/LitterRally#75]
**Task Description**

As a developer I want to have back-end GraphQL queries to:
- Discover relevant events
- See upcoming events a user has joined
- See events hosted by a user 

**Acceptance Criteria**
- [ ] Events are ordered by event start date
- [ ] Able to query relevant events, upcoming events and events hosted by a user
- [ ] Documentation present for every new component and function where necessary
- [ ] Unit tests implemented for every function

*Hardcoded users for this task is sufficient
*Relevant events can be querying all events for this task
