### ISSUE TITLE
TASK-1: Setup Testing Infrastructure (Unit, Snapshot, and E2E Tests)

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#8]
**Task Description**

As a developer, I want to setup a basic and functional testing infrastructure so that other developers can build on top of this testing foundation.

**Acceptance Criteria**
Make sure all testing is setup before development starts:
- [x] Setup Jest unit tests
- [x] Setup Cypress e2e tests
- [x] Setup React Test Renderer UI snapshot tests
- [x] Travis runs tests that are runnable on CI

**Comment by RGPosadas** [comment]
For Storybook in an nx workspace: https://nx.dev/angular/plugins/storybook/overview/
